### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by JulienJo** [Magiczne/JD-XI-Editor#1]
Hi! Sorry for the dumb question but... How to load the program? Do I need a compiler or a command line or something else?

**Comment by Magiczne** [comment]
Hi! Yes, you need a Visual Studio to open and compile the project. I will create release with downloadable .exe today if i find some time

**Comment by Magiczne** [comment]
Here it is

https://github.com/Magiczne/JD-XI-Editor/releases/tag/v0.1.1

**Comment by Magiczne** [comment]
As well as v0.1.2 which includes updated for all used libraries
