### ISSUE TITLE
Saving and loading patches

### ISSUE THREAD

**Issue by Zalastax** [Magiczne/JD-XI-Editor#3]
Great work on this editor! It's very intuitive and much more stable than the alternatives that I have tried.

In the README.md, I see that Saving patches to file and Loading patches from file are planned. This would be hugely appreciated.

I had a look and it should not be too difficult to add this capability to the Patch.cs files, but I don't feel ready to take the plunge and start implementing it. For now, just see this as a thanks for great work so far and hopefully some motivation.

**Comment by Magiczne** [comment]
Thanks a lot! That was the reason I made this. Every editor I've tried basically was garbage. Either looked like it or behaved like it ;-)

Currently I don't have access to my JDXI so cannot update it with all planned features. Maybe will try to do a blind update with patch saving as this should not require physical device, but I don't know when I will have time for that. Anyways if you can do something with code go on, make a PR, and that will be probably a better kickstart for me to finish it.

**Comment by Magiczne** [comment]
Actually, made the UI changes already in the master branch. Maybe I'll finish it this week.

**Comment by Magiczne** [comment]
@Zalastax 

Loading and saving for almost every patch is currently on master branch, you can compile it yourself and try, FX tab loading data is currently not working as there are some problem with polymorphism. Will try to fix that, but in the meantime you can try other tabs ;-)

EDIT: Actually, figured it out. Pushing new version. If you find some bugs, just create new issue.

**Comment by Zalastax** [comment]
Wow! That was amazingly fast! Very kind of you @Magiczne 🥇💟🥇

I've tested it and it works great 😃
