### ISSUE TITLE
Save / load patches should use YAML Fileformat in the dialog

### ISSUE THREAD

**Issue by Zalastax** [Magiczne/JD-XI-Editor#4]
When saving / loading patches, YAML files are used but this is not reflected in the dialog (Fileformat is empty):
![bild](https://user-images.githubusercontent.com/908496/210263075-f8e499c6-8779-4777-a6eb-265f334dea3b.png)

Submitting this just so it is known. Not an important issue for me.

**Comment by Magiczne** [comment]
Fixed in 0f10fde
