### ISSUE TITLE
Loading patch for the wrong tab crashes the editor

### ISSUE THREAD

**Issue by Zalastax** [Magiczne/JD-XI-Editor#5]
If I save a patch from Digitial Synth 1 and load it in Digitial Synth 2 there is no problem since they use the same parameters.
But if I load the same patch in Drums, the application will exit silently.

Submitting this just so it is known. Not an important issue for me.

**Comment by Magiczne** [comment]
Fixed in 22185c4


@Zalastax v0.2.1 will come in a few minutes.
